"""
Auto-generated list of all people in the family tree.
Generated from: <user-tree-root>/People/*

This file is for development/testing purposes.
In production, this list should be loaded from the configuration file.
"""

# List of all person folder names from the sorted tree
ALL_PEOPLE = [
    "(nieznane) (nieznane)",
    "(nieznane) (nieznane) (mężczyzna)",
    "(nieznane) (nieznane) zd. (nieznane)",
    "(nieznane) (nieznane) zd. (nieznane) - żona Stanisława Gładysza(2)",
    "(nieznane) (nieznane) zd. (nieznane) (1)",
    "(nieznane) (nieznane) zd. (nieznane) (2)",
    "(nieznane) (nieznane) zd. Paziewska",
    "(nieznane) (nieznane) zd. Wasilewska",
    "(nieznane) Cwyl",
    "(nieznane) Gładysz",
    "(nieznane) Kominek;Kuminek (1)",
    "(nieznane) Kominek;Kuminek (2)",
    "(nieznane) Kossowska zd. (nieznane)",
    "(nieznane) Kossowski",
    "(nieznane) Kowalska",
    "(nieznane) Kowalski",
    "(nieznane) Lewandowski",
    "(nieznane) Łodzkiewicz",
    "(nieznane) Łodzkiewicz zd. (nieznane)",
    "(nieznane) Małecki (1)",
    "(nieznane) Małecki (2)",
    "(nieznane) Manke",
    "(nieznane) Mankin",
    "(nieznane) Pełnikowski",
    "(nieznane) Radzińska zd. Śliwińska",
    "(nieznane) Sadowski",
    "(nieznane) Staluszka",
    "(nieznane) Staluszka zd. (nieznane) (1)",
    "(nieznane) Staluszka zd. (nieznane) (2)",
    "(nieznane) Wasilewska zd. Gładysz",
    "Adam (nieznane)vPastryk - matka Danuta Pastryk",
    "Adam Mankin",
    "Adam Oleksy",
    "Adam Rutowski",
    "Adela Cwyl zd. Staluszka",
    "Adrian Kowalski",
    "Agata (nieznane) zd. Olewnik",
    "Agata Łodzkiewicz zd. Krzeszewska",
    "Agnieszka Jakubowska zd. Smerecka",
    "Agnieszka Karpińska zd. Ziemińska",
    "Agnieszka Łuciuk zd. (nieznane) - matka Danuta Pastryk",
    "Aleksander Matynka",
    "Alicja Jesionowska zd. Olewnik",
    "Alicja Sobierajska zd. (nieznane)",
    "Anastazja Śpiewakowska zd. Czajkowska",
    "Andrzej Krankiewicz",
    "Andrzej Staluszka",
    "Andrzej Ziemiński",
    "Aneta Stefaniszyn zd. Pastryk",
    "Aneta Ziemińska zd. (nieznane)",
    "Aniela (nieznane) zd. Cwyl",
    "Anna (nieznane) zd. Czajkowska",
    "Anna (nieznane) zd. Kuziel",
    "Anna Lewandowska zd. Matynka",
    "Anna Mankin;Manke zd. (nieznane)",
    "Anna Pietrzak zd. Matynka",
    "Anna Staluszka zd. Srzednicka",
    "Antoni Krankiewicz",
    "Antoni Stanuch",
    "Antonina Hys zd. Staluszka",
    "Apolonia Śliwińska zd. Lemańska",
    "Arkadiusz Hołubek",
    "Arkadiusz Olejnik",
    "Artur (nieznane)vPastryk - matka Danuta Pastryk",
    "Artur Sobierajski",
    "Barbara Stanuch zd. (nieznane)",
    "Bartek Manke",
    "Błażej Czajkowski",
    "Bogdan Kowalski",
    "Bogdan Olewnik",
    "Bogdan Szwech",
    "Bogusława Chrzanowska zd. Kubicka",
    "Bolesław Manke",
    "Bolesław Rutowski",
    "Bolesław Zajkowski",
    "Bolesława Szwech zd. Rutowska",
    "Bożena Galaszewska zd. Mankin",
    "Bożena Oleksy zd. Smerecka",
    "Bożena Ziemińska zd. Pełnikowska",
    "Bronisław Staluszka",
    "Bronisława (nieznane) zd. Staluszka",
    "Bruno Pastryk",
    "Czesława Kubicka zd. Rutowska",
    "Danuta (nieznane) zd. Pastryk",
    "Danuta Kowalska zd. Łodzkiewicz",
    "Danuta Zaremba zd. Misiak",
    "Darek Surus",
    "Dawid Łodzkiewicz",
    "Dominik (nieznane)vPastryk",
    "Dzidka Podremańska zd. Biela",
    "Elżbieta Surus zd. Sobierajska",
    "Eryk Srzednicki",
    "Ewa (nieznane) zd. Krankiewicz",
    "Ewa (nieznane)vPastryk - matka Danuta Pastryk",
    "Ewa Fiutka zd. Srzednicka",
    "Ewa Sobierajska",
    "Feliks Sobierajski",
    "Feliksa Rutowska zd. Łazińska",
    "Florian Łędkowski",
    "Franciszek Krankiewicz",
    "Franciszek Manke",
    "Franciszek Matynka",
    "Franciszek Rutowski",
    "Franciszek Śliwiński",
    "Franciszek Staluszka",
    "Franciszka Śliwińska zd. Skowrońska",
    "Franciszka Srzednicka zd. Kuziel",
    "Franciszka Staluszka zd. Bogucka",
    "Genowefa Mańturzyk zd. Staluszka",
    "Genowefa Srzednicka zd. (nieznane)",
    "Grażyna Smerecka",
    "Halina Mankin",
    "Halina Sobierajska zd. Sacharowska",
    "Halina Świerczyńska zd. (niewiadomo)",
    "Helena (nieznane) zd. Kuziel",
    "Helena Misiak zd. Rutowska",
    "Ignacy Kominek;Kuminek",
    "Ignacy Staluszka",
    "Ilona Legut zd. Pastryk",
    "Inga Szubert zd. Hołubek",
    "Irena (nieznane) zd. Biela",
    "Irena Pastryk zd. Mankin;Manke",
    "Ireneusz Pastryk",
    "Iwan Śpiewakowski",
    "Izabela (nieznane) zd. Hołubek",
    "Jacek (nieznane)vPastryk - matka Danuta Pastryk",
    "Jadwiga Czapska zd. Kubicka",
    "Jadwiga Hajduk zd. (nieznane)",
    "Jadwiga Manke zd. (nieznane)",
    "Jadwiga Mankin zd. Staluszka",
    "Jadwiga Smerecka zd. Srzednicka",
    "Jadwiga Sternalska zd. Stanuch",
    "Jakub Krankiewicz",
    "Jan Chrzanowski",
    "Jan Gładysz",
    "Jan Gwalbert Krankiewicz",
    "Jan Krankiewicz",
    "Jan Łodzkiewicz",
    "Jan Matynka (1)",
    "Jan Matynka (2)",
    "Jan Śliwiński (1)",
    "Jan Śliwiński (2)",
    "Jan Sobierajski",
    "Jan Srzednicki (1)",
    "Jan Srzednicki (2)",
    "Jan Wasilewski",
    "Janina (nieznane) zd. Gładysz",
    "Janina Baranowska zd. Szwech",
    "Janina Sobierajska zd. Rutowska",
    "Janina Szydłowska zd. Staluszka",
    "Jerzy Chrzanowski",
    "Jerzy Galaszewski",
    "Jerzy Hołubek",
    "Jerzy Kubicki",
    "Jerzy Łodzkiewicz",
    "Jerzy Mankin",
    "Jerzy Srzednicki",
    "Joanna Manke zd. (nieznane)",
    "Józef Kalwasiński",
    "Józef Krankiewicz",
    "Józef Mańturzyk",
    "Józef Misiak",
    "Józef Pełnikowski",
    "Józef Rutowski",
    "Józef Śliwiński",
    "Józefa (nieznane) zd. Czajkowska",
    "Józefa Kalwasińka zd. Rutowska",
    "Józefa Małecka zd. Gładysz",
    "Józefa Modziejewska zd. Krankiewicz",
    "Józefa Rutowska zd. Matynka",
    "Józefa Staluszka zd. Szeląg",
    "Julian Mankin;Manke",
    "Julian Srzednicki",
    "Julianna (nieznane) zd. Rutowska",
    "Julianna Czajkowska zd. Łędkowska",
    "Julianna Staluszka zd. Paziewska",
    "Jurek Mankin",
    "Kamil Sobierajski",
    "Kamila (nieznane) zd. Oleksy",
    "Kamila (nieznane) zd. Stanuch",
    "Katarzyna (nieznane) zd. Rutowska",
    "Katarzyna (nieznane) zd. Śliwińska",
    "Katarzyna Julianna (nieznane) zd. Czajkowska",
    "Katarzyna Matynka zd. Krankiewicz",
    "Katarzyna Rutowska zd. Sadowska",
    "Katarzyna Sadowska zd. Sułkowska",
    "Katarzyna Szafran zd. Mankin",
    "Kazimiera Rutowska zd. Misiak",
    "Kazimierz Czajkowski",
    "Kazimierz Mankin",
    "Kinga Kaseja zd. Smerecka",
    "Konrad Galaszewski",
    "Konstanty Śliwiński",
    "Krystyna Woźniakowska zd. Rutowska",
    "Kunegunda Kuziel zd. Kossowska",
    "Leokadia (nieznane) zd. Misiak",
    "Leokadia Łodzkiewicz zd. Rutowska",
    "Leokadia Markowska zd. Staluszka",
    "Leokadia Matynka",
    "Leon Kuziel",
    "Leon Rutowski",
    "Leszek Mankin",
    "Leszek Sobierajski",
    "Lidia Sobierajska zd. Hajduk",
    "Łucja Srzednicka",
    "Lucjan Srzednicki",
    "Lucyna Mankin zd. Salomon;Salamon",
    "Łukasz (nieznane)vPastryk - matka Danuta Pastryk",
    "Łukasz Manke",
    "Łukasz Pastryk",
    "Łukasz Sternalski",
    "Maciej Stanuch",
    "Maciek Oleksy",
    "Magdalena (nieznane) zd. Rutowska",
    "Magdalena Pasierb-Skoczylas zd. (nieznane)vPastryk - matka Danuta Pastryk",
    "Małgorzata (nieznane) zd.  Srzednicka",
    "Małgorzata Łędkowska zd. (nieznane)",
    "Małgorzata Staluszka zd. Gładysz",
    "Marcin Dydak",
    "Marcin Manke",
    "Marcin Matynka",
    "Marcin Staluszka (1)",
    "Marcin Staluszka (2)",
    "Marcjanna Kowalska zd. Śpiewakowska",
    "Marcjanna Matynka zd. (nieznane)",
    "Marek (nieznane)vPastryk - matka Danuta Pastryk",
    "Marek Smerecki",
    "Maria (nieznane) zd. Matynka",
    "Maria Biela zd. Kuziel",
    "Maria Dębek zd. Gładysz",
    "Maria Hołubek zd. Mańturzyk",
    "Maria Sławska zd. Kossowska",
    "Marian Krankiewicz",
    "Marian Matynka",
    "Marian Srzednicki (1)",
    "Marian Srzednicki (2)",
    "Marianna (nieznane) zd. Krankiewicz (1)",
    "Marianna (nieznane) zd. Krankiewicz (2)",
    "Marianna (nieznane) zd. Staluszka",
    "Marianna Czajkowska zd. Gałczyńska",
    "Marianna Gładysz zd. Paziewska",
    "Marianna Kominek;Kuminek zd. Mikołajczyk",
    "Marianna Krankiewicz zd. Matynka",
    "Marianna Matynka",
    "Marianna Mroczek zd. Staluszka",
    "Marianna Olewnik zd. Rutowska",
    "Marianna Rutowska zd. Alabrudzińska",
    "Marianna Sobierajska zd. Człapińska",
    "Mariusz Pastryk",
    "Marta (nieznane) zd. (nieznane)vPastryk - matka Danuta Pastryk",
    "Mateusz Krankiewicz",
    "Michał (nieznane)vPastryk - matka Danuta Pastryk",
    "Michał Manke",
    "Michał Matynka",
    "Mieczysław Hajduk",
    "Mieczysław Olewnik",
    "Mirosław Łodzkiewicz",
    "Mirosław Stanuch",
    "Monika Kowalska zd. (nieznane)",
    "Nikodem Pastryk",
    "Paulina Kowalska",
    "Paweł Chrzanowski",
    "Paweł Manke",
    "Paweł Rutowski",
    "Paweł Srzednicki",
    "Piotr Staluszka",
    "Piotrek Smerecki",
    "Przemysław (nieznane)vPastryk - matka Danuta Pastryk",
    "Przemysław Łodzkiewicz",
    "Regina Misiak zd. Rutowska",
    "Renata Łodzkiewicz zd. (nieznane)",
    "Robert Hołubek",
    "Robert Ziemiński",
    "Roman Mankin",
    "Roman Rutowski",
    "Roman Staluszka",
    "Ryszard Manke",
    "Ryszard Mankin",
    "Ryszard Pastryk",
    "Ryszard Surus",
    "Ryszard Ziemiński",
    "Ryszarda Biela zd. Srzednicka",
    "Sebastian Kowalski",
    "Sebastian Kuziel",
    "Sławomir Kaseja",
    "Stanisław Cwyl",
    "Stanisław Czajkowski (1)",
    "Stanisław Czajkowski (2)",
    "Stanisław Czapski",
    "Stanisław Gładysz (1)",
    "Stanisław Gładysz (2)",
    "Stanisław Lewandowski",
    "Stanisław Mankin;Manke",
    "Stanisław Mroczek",
    "Stanisław Olewnik",
    "Stanisław Pastryk (1)",
    "Stanisław Pastryk (2)",
    "Stanisław Staluszka (1)",
    "Stanisław Staluszka (2)",
    "Stanisława (nieznane) zd. Rutowska",
    "Stanisława (nieznane) zd. Staluszka",
    "Stanisława Górecka zd. Szwech",
    "Stanisława Mankin;Manke",
    "Stanisława Srzednicka zd. (nieznane)",
    "Stefania (nieznane) zd. Kuziel",
    "Sylwester (nieznane)vPastryk - matka Danuta Pastryk",
    "Sylwia Maria Omiotek zd. (nieznane)vPastryk - matka Danuta Pastryk",
    "Sylwia Misiak zd. Galaszewska",
    "Sylwia Sobierajska zd. (nieznane)",
    "Sylwia Zastawnik zd. Sternalska",
    "Szczepan Matynka",
    "Szymon Czajkowski",
    "Tekla Dydak zd. (nieznane)",
    "Tekla Rutowska zd. Śliwińska",
    "Teofila Matynka zd. Dydak;Dydo",
    "Teresa Lewandowska zd. Kubicka",
    "Tomasz Kossowski",
    "Tomasz Mankin",
    "Tomasz Pastryk",
    "Tomasz Smerecki",
    "Tomasz Surus",
    "Urszula Zamaria zd. Srzednicka",
    "Wacław Mańturzyk",
    "Wacław Staluszka",
    "Wacława Pełnikowska zd. Mankin;Manke",
    "Waldemar Manke",
    "Waleria Rutowska",
    "Wanda (nieznane) zd. Matynka",
    "Wanda (nieznane) zd. Szwech",
    "Wanda Manke zd. (nieznane)",
    "Wawrzyniec Śliwiński",
    "Weronika Zimna zd. Krankiewicz",
    "Wiktoria Kossowska zd. (nieznane)",
    "Witold Srzednicki",
    "Witold Staluszka",
    "Władysław Staluszka (1)",
    "Władysław Staluszka (2)",
    "Władysław Staluszka (3)",
    "Władysław Staluszka (4)",
    "Władysław Staluszka (5)",
    "Władysław Szwech",
    "Władysława (nieznane) zd. Kuziel",
    "Władysława Mankin;Manke zd. Kuminek;Kominek",
    "Władysława Szwech",
    "Wojciech (nieznane)vPastryk - matka Danuta Pastryk",
    "Wojciech Czajkowski",
    "Wojciech Krankiewicz",
    "Zbigniew Chrzanowski",
    "Zbigniew Mankin",
    "Zofia (nieznane) zd. Kuziel",
    "Zofia Mankin zd. Rutowska",
    "Zofia Matynka zd. (nieznane)",
    "Zofia Stanuch zd. Srzednicka",
    "Zofia Zajkowska zd. Olewnik",
]

# Total count
TOTAL_PEOPLE_COUNT = len(ALL_PEOPLE)
